# Github action to handle Github Actions's changes in CICD
name: CI/CD - Build pdf

on: [push]
  # # define under which branchesand folder the changes needs to be made to trigger the action
  # push:
  #   branches:
  #   - master
  #   - acceptance
  #   - test
  
  #   paths:
  #   - tools/github-actions-runner/bootstrap.sh

# env:
#   S3_BUCKET: vdb-core-digital-serv-infra

jobs:
  build_pdf:

    runs-on: [self-hosted]

    steps:

      - name: Checkout branch 
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Build CV pdf
        run: |
          docker-compose run tex-compiler xelatex cv.tex
      # - name: Pack and deploy bootstrap.sh
      #   run: |
      #     aws s3 cp tools/github-actions-runner/bootstrap.sh s3://${{ env.S3_BUCKET }}/actions_runner --acl public-read
      #     aws s3api put-object-tagging --key actions_runner/bootstrap.sh --bucket ${{ env.S3_BUCKET }} --tagging 'TagSet=[{Key=version, Value=${{ github.sha }}},{Key=application, Value=actions_runner}]'

      - uses: actions/upload-artifact@v2
        with:
          name: cv
          path: cv/cv.pdf